// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: executeGreeting/executeGreeting.proto

package executeGreeting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteGreetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExecuteGreetingRequest) Reset() {
	*x = ExecuteGreetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_executeGreeting_executeGreeting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGreetingRequest) ProtoMessage() {}

func (x *ExecuteGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_executeGreeting_executeGreeting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGreetingRequest.ProtoReflect.Descriptor instead.
func (*ExecuteGreetingRequest) Descriptor() ([]byte, []int) {
	return file_executeGreeting_executeGreeting_proto_rawDescGZIP(), []int{0}
}

type ExecuteGreetingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ExecuteGreetingReply) Reset() {
	*x = ExecuteGreetingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_executeGreeting_executeGreeting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteGreetingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGreetingReply) ProtoMessage() {}

func (x *ExecuteGreetingReply) ProtoReflect() protoreflect.Message {
	mi := &file_executeGreeting_executeGreeting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGreetingReply.ProtoReflect.Descriptor instead.
func (*ExecuteGreetingReply) Descriptor() ([]byte, []int) {
	return file_executeGreeting_executeGreeting_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteGreetingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_executeGreeting_executeGreeting_proto protoreflect.FileDescriptor

var file_executeGreeting_executeGreeting_proto_rawDesc = []byte{
	0x0a, 0x25, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x30, 0x0a,
	0x14, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x6c, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x12, 0x59, 0x0a, 0x0f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x47, 0x72,
	0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x6c, 0x0a,
	0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3a, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f,
	0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73,
	0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_executeGreeting_executeGreeting_proto_rawDescOnce sync.Once
	file_executeGreeting_executeGreeting_proto_rawDescData = file_executeGreeting_executeGreeting_proto_rawDesc
)

func file_executeGreeting_executeGreeting_proto_rawDescGZIP() []byte {
	file_executeGreeting_executeGreeting_proto_rawDescOnce.Do(func() {
		file_executeGreeting_executeGreeting_proto_rawDescData = protoimpl.X.CompressGZIP(file_executeGreeting_executeGreeting_proto_rawDescData)
	})
	return file_executeGreeting_executeGreeting_proto_rawDescData
}

var file_executeGreeting_executeGreeting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_executeGreeting_executeGreeting_proto_goTypes = []interface{}{
	(*ExecuteGreetingRequest)(nil), // 0: helloworld.ExecuteGreetingRequest
	(*ExecuteGreetingReply)(nil),   // 1: helloworld.ExecuteGreetingReply
}
var file_executeGreeting_executeGreeting_proto_depIdxs = []int32{
	0, // 0: helloworld.ExecuteGreeting.ExecuteGreeting:input_type -> helloworld.ExecuteGreetingRequest
	1, // 1: helloworld.ExecuteGreeting.ExecuteGreeting:output_type -> helloworld.ExecuteGreetingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_executeGreeting_executeGreeting_proto_init() }
func file_executeGreeting_executeGreeting_proto_init() {
	if File_executeGreeting_executeGreeting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_executeGreeting_executeGreeting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteGreetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_executeGreeting_executeGreeting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteGreetingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_executeGreeting_executeGreeting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_executeGreeting_executeGreeting_proto_goTypes,
		DependencyIndexes: file_executeGreeting_executeGreeting_proto_depIdxs,
		MessageInfos:      file_executeGreeting_executeGreeting_proto_msgTypes,
	}.Build()
	File_executeGreeting_executeGreeting_proto = out.File
	file_executeGreeting_executeGreeting_proto_rawDesc = nil
	file_executeGreeting_executeGreeting_proto_goTypes = nil
	file_executeGreeting_executeGreeting_proto_depIdxs = nil
}
